name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}] # every Sunday
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # REQUIRED: GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # ğŸ—“ï¸ Commit calendar plugin
          plugin_calendar: yes
          plugin_calendar_limit: 0 # change this as per your preference

          # You can also enable other plugins here
